spring:
  application:
    name: Spring REST API Template for GCP.
  # Database Configuration - postgresql
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8090
  servlet:
    context-path: /template

app:
  pubsub:
    topic: sample-events

# Logging Configuration
logging:
  level:
    root: INFO
    com.google.cloud.pubsub: INFO
    org.springframework.cloud.gcp.pubsub: INFO
    org.springframework.integration: INFO
