spring:
  # Cloud GPC Configuration
  cloud:
    gcp:
      project-id: sample-project
      pubsub:
        emulator-host: localhost:8085
        enabled: true
      credentials:
        enabled: false
  # Database Configuration - postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/north
    username: ${DB_USERNAME:usr_north}
    password: ${DB_PASSWORD:Pass1234}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

#  GPC PubSub Configuration
app:
  pubsub:
    topic: sample-topic

# Logging Configuration for Local Profile
logging:
  level:
    root: INFO
    com.google.cloud.pubsub: DEBUG
    org.springframework.cloud.gcp.pubsub: DEBUG
    org.springframework.integration: DEBUG
